language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
install:
 - wget https://bootstrap.pypa.io/ez_setup.py -O - | python
 - pip install -r requirements.txt
script: python -m unittest
notifications:
  slack:
    secure: HPf1xQoHknIAD5PxhQE8vL0wF774UqLG/sZRl1iaTfOHvkkkHJ8vapNHx85MhzBu8z77YTa6+oIqV5MPYx3qEM07btTZp4xoBSjWtkNcN3jognD/2X7kgRKsvLmIVkbHIps6byPDujTxsonNUgxa9YdT8yOHBJhNQ95iFRXCQJYEK9Y7SqEjo5E7VYCelX3fmmISIPZkykX0Jfs774ndVvCN2PRi54bGEXHzaiBuKsB0Aq2GBpCEl+M2uaH03BzLDEdj+Jd+onARGWqj3oO3GEoxOd4sw7WlQiLRoAznvVSqXTxYOMoC8JHhnaWeT9QLKn9gbqo+EHIU7M31hnKFXlohnzL7Sb/kt0CND7f1W51bgOeIExFP7sHa8qDwMMuq7mbA7bfDwjR3GxAfhZabtYR8a7wrRU9YehYFznXX5+mGiXQPEgIpnJR3Pagv1fyc0dFGPD2SvhhVfXqxeJTl7bPs/t4HR+sBwDCkIEmZobEykmLchYnyX64Gi7xdMXWU5SC675hd4ce3hKGp8l/h01g28Ebyf2kgR9IcC1toPXEGzwE8J/Mx39kWdwVzJ1ZUUaPvVuancW5GsgQtR2sf1HJlswIVhjaQeliCe+2Ju64anUISWs8h6AhoY4qTNm5pVtyW5FUN+3srfVHG/HtX0dMldcj4uSgrMSDJEnq5XRU=
